version: '3'

services:
    mercure:
        image: dunglas/mercure
        container_name: mercure
        env_file:
            - .env # always load as general configuration
            - .env.${APP_ENV:-dev} # load override by stage, default to dev
