version: '3'

services:
    mercure:
        restart: unless-stopped
        labels:
            - traefik.enable=true
            - traefik.http.routers.mercure.tls=true
            - traefik.http.routers.mercure.rule=Host(`mercure.emokykla.win`)
            - traefik.http.routers.mercure.service=mercure
            - traefik.http.services.mercure.loadbalancer.server.port=80
        networks:
            - traefik
networks:
    traefik:
        external: true

