version: '3'

services:
    mercure:
        # https://github.com/dunglas/mercure/releases
        image: dunglas/mercure:v0.10.4
        container_name: mercure
        env_file:
            - .env # always load as general configuration
            - .env.${APP_ENV:-dev} # load override by stage, default to dev
